/*
(ռուսերեն)
<br>1////////////////////////////////////////////////////////////////////////////////////<br>
<br>https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Number
<br>https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/String
<br>https://developer.mozilla.org/ru/docs/Web/JavaScript/Guide/Expressions_and_Operators
<br>2////////////////////////////////////////////////////////////////////////////////////<br>
<br>https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Statements/if...else
<br>https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Statements/switch
<br>3///////////////////////////////////////////////////////////////////////////////////<br>
<br>https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Statements/for
<br>4///////////////////////////////////////////////////////////////////////////////////<br>
<br>https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Statements/while
<br>https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Statements/do...while
<br>5///////////////////////////////////////////////////////////////////////////////////<br>
<br>https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array
<br>6///////////////////////////////////////////////////////////////////////////////////<br>
<br>https://learn.javascript.ru/object    -   մինչև «Свойство из переменной» ենթավերնագիր,
<br>https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Object/keys,
<br>https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Object/values
<br>https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Object/entries
<br>7///////////////////////////////////////////////////////////////////////////////////<br>
<br>https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment
<br>https://learn.javascript.ru/function-basics
<br>8///////////////////////////////////////////////////////////////////////////////////<br>
<br>https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Functions/Arrow_functions
<br>https://developer.mozilla.org/ru/docs/Web/JavaScript/Closures
<br>https://learn.javascript.ru/recursion
<br>9///////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////
10///////////////////////////////////////////////////////////////////////////////////
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/map
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/filter
11///////////////////////////////////////////////////////////////////////////////////
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/sort
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce
*/